project:
  type: website

website:
  title: "Weizhu Pan"
  description: "Resume of Weizhu Pan."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    title: "Weizhu Pan"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



